name: Deploy Lambda with Terraform

on:
  push:
    branches: [ main, dev ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::975049962487:role/cas3135-2025000001-gha-role
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: github-actions-terraform
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=cas3135-2025-tfstates" \
          -backend-config="key=cas3135-2025000001/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=cas3135-terraform-locks"
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Terraform Plan
      run: terraform plan -var="aws_region=${{ env.AWS_REGION }}"
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -var="aws_region=${{ env.AWS_REGION }}"